site_name: Design Docs
theme:
  name: material
  language: ja
  features:
    - content.code.copy
plugins:
  - search

markdown_extensions:
  # コードハイライト
  - pymdownx.highlight:
      auto_title: true
      linenums: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
